### ISSUE TITLE
Implement Presentation Request

### ISSUE THREAD

**Issue by karstensfriis** [felleslosninger/dc24-wallet-verifier#10]
```[tasklist]
### Tasks
- [ ] Access a Mattr token (already implemented in the Issuer repo)
- [ ] Presentation Template
- [ ] Presentation Request
- [ ] Controller to handle .env variables
- [ ] Convert URI to QR code
```
